spring:
  datasource:
    url: jdbc:postgresql://db:5432/bankcards
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/migration/db.migration-master.yaml
    enabled: true